### ISSUE TITLE
Mobile Device?

### ISSUE THREAD

**Issue by sahil48** [ahmedelq/NattyNote#2]
Is there any sort of bookmarklet or Safari Extension we could use to run NattyNote on iOS Safari browser?

**Comment by ahmedelq** [comment]
It seems that Safari runs only on IOS devices. I'm using a Linux distro! I'm not sure if the chrome version will work since chrome and safari are forks of WebKit. 

You could try it, download `chrome.zip` from the releases, see how to load a temporary extension in Safari and check if it's working.
https://github.com/ahmedelq/NattyNote/releases

As I said, I don't have a Macintosh machine so I can't currently work on it. Maybe we could find someone who does.
